### ISSUE TITLE
cool - why did you develop this?

### ISSUE THREAD

**Issue by yachty66** [dannylee1020/openpo#1]

**Comment by dannylee1020** [comment]
@yachty66 Hey! I initially started looking into synthetic data generation out of curiosity from learning that high quality data is the biggest bottleneck in AI development. Then as I learned more, I realized it is one of few areas where an open source project could make impact to the community without needing a lot of resources (compute, for example). 

Hypothesis I currently have, and still in progress of validating is: If AI agent is believed to replace human labor in various ways, why not in data generation?

**Comment by yachty66** [comment]
This makes a lot of sense to me. 

Something I am curious about:

Most of the companies like scale.com feel like they are more B2B businesses, which makes a lot of sense to me because why would a consumer pay for this?

**Comment by dannylee1020** [comment]
B2B definitely makes sense if this were to become a business. For now, the primary goal is to contribute to the AI open source ecosystem.

**Comment by yachty66** [comment]
Yeah, but in the end, if someone is willing to pay for it, it's the best validation of whether it's a useful tool or not. I was thinking about how the UX/UI would look for this, and I was considering something like https://bolt.new or https://lovable.dev.

These two example products are definitely customer-facing products, and I wonder if such an interface would work for datasets instead of apps.

**Comment by dannylee1020** [comment]
Interesting. Haven't thought about the UI component of this project yet. However, if the project is targeted specifically for devleopers building in AI, I am not sure if having a chat interface would be very beneficial (need validation of course). 

There have been many open-source models finetuned on synthetic data ([OpenHermes](https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B) for example), so my next move is to understand how they built the dataset. We can take this conversation offline if you want to chat more about it!
